# Generated by Django 4.1.1 on 2022-12-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
